name: Release

on:
  push:
    tags:
      - "*.*.*"

# Allow creating releases and packages.
permissions:
  packages: write
  contents: write

jobs:
  goreleaser:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # v3.3.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}

      - name: Prepare GPG signing key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" > key.gpg

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          NFPM_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
          NFPM_TESTPKG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}

      - name: Test packages
        run: ./tests/packages/run-tests.sh

  docker-hub-doc:
    name: Publish DockerHub Readme
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/web-indexer
          readme: ./README.md
          description: Generate file indexes for directories and S3 buckets
